// State-wise government schemes for Indian farmers
export const STATE_SCHEMES = {
  "Andhra Pradesh": [
    "🌾 Rytu Bandhu (Farm Assistance)",
    "🌱 Soil Health Card Scheme",
    "💧 Pradhan Mantri Krishi Sinchayee Yojana",
    "🛡️ PMFBY (Crop Insurance)",
    "🌿 Green India Mission",
  ],
  "Arunachal Pradesh": [
    "🌾 Pradhan Mantri Kisan Samman Nidhi",
    "🌱 State Agriculture Mission",
    "💧 Flood Management Scheme",
    "🛡️ Crop Insurance Scheme",
    "🚜 Farm Mechanization Support",
  ],
  "Assam": [
    "🌾 Aam Aadmi Bima Yojana",
    "🌱 Jabo Aashan (Agriculture Support)",
    "💧 Irrigation Development Scheme",
    "🛡️ PMFBY Crop Insurance",
    "🌿 Agricultural Produce Market Committee",
  ],
  "Bihar": [
    "🌾 Pradhan Mantri Kisan Samman Nidhi",
    "🌱 Mukhya Mantri Kanya Utthan Yojana",
    "💧 Jal Jeevan Hariyali",
    "🛡️ Fasal Bima Yojana",
    "🚜 Zero Budget Natural Farming",
  ],
  "Chhattisgarh": [
    "🌾 Godhan Nyay Yojana",
    "🌱 Narva, Garva, Ghurva Programme",
    "💧 Mahatma Gandhi NREGA",
    "🛡️ Crop Insurance Scheme",
    "🌿 Organic Farming Mission",
  ],
  "Goa": [
    "🌾 Pradhan Mantri Kisan Samman Nidhi",
    "🌱 State Horticulture Mission",
    "💧 Coconut Development Board",
    "🛡️ Crop Insurance Support",
    "🌿 Spice Development Scheme",
  ],
  "Gujarat": [
    "🌾 Pradhan Mantri Kisan Samman Nidhi",
    "🌱 Soil Health Card Scheme",
    "💧 PMKSY Micro Irrigation",
    "🛡️ Government Crop Insurance",
    "🌿 Sardar Krusak Yojana",
  ],
  "Haryana": [
    "🌾 Pradhan Mantri Kisan Samman Nidhi",
    "🌱 Meri Pari Scheme",
    "💧 PMKSY Irrigation Scheme",
    "🛡️ PMFBY Crop Insurance",
    "🌿 Mera Pani Meri Virasat",
  ],
  "Himachal Pradesh": [
    "🌾 Himachal Pradesh Agricultural Support",
    "🌱 Horticulture Development Scheme",
    "💧 Watershed Development",
    "🛡️ Crop Insurance Yojana",
    "🌿 Organic Farming Support",
  ],
  "Jharkhand": [
    "🌾 Pradhan Mantri Kisan Samman Nidhi",
    "🌱 Surya Mitran Scheme",
    "💧 PMKSY Watershed",
    "🛡️ Fasal Bima Yojana",
    "🚜 Farm Mechanization Support",
  ],
  "Karnataka": [
    "🌾 Raita Bandhu Scheme",
    "🌱 Soil Health Mission",
    "💧 Pradhan Mantri ASBY",
    "🛡️ Fasal Bima Yojana",
    "🌿 Agricultural Mechanization",
  ],
  "Kerala": [
    "🌾 Pradhan Mantri Kisan Samman Nidhi",
    "🌱 Spice Board Support",
    "💧 Micro Irrigation Scheme",
    "🛡️ Coconut Replantation Scheme",
    "🌿 Cashew Development",
  ],
  "Madhya Pradesh": [
    "🌾 Pradhan Mantri Kisan Samman Nidhi",
    "🌱 Bhavantar Bhugtan Yojana",
    "💧 PMKSY Irrigation Development",
    "🛡️ Crop Insurance Protection",
    "🌿 Digital Solution for Farmers",
  ],
  "Maharashtra": [
    "🌾 Pradhan Mantri Kisan Samman Nidhi",
    "🌱 Sugarcane Support Scheme",
    "💧 Jal Jeevan Hariyali",
    "🛡️ Government Crop Insurance",
    "🌿 Organic Certificate Support",
  ],
  "Manipur": [
    "🌾 State Agriculture Support",
    "🌱 Horticulture Development",
    "💧 Irrigation Development Scheme",
    "🛡️ Crop Insurance Yojana",
    "🌿 Organic Farming Promotion",
  ],
  "Meghalaya": [
    "🌾 Pradhan Mantri Kisan Samman Nidhi",
    "🌱 State Horticulture Mission",
    "💧 Watershed Development",
    "🛡️ Crop Insurance Support",
    "🌿 Beekeeping Support",
  ],
  "Mizoram": [
    "🌾 State Agriculture Support",
    "🌱 Horticulture Development Scheme",
    "💧 Irrigation Infrastructure",
    "🛡️ Crop Insurance Yojana",
    "🌿 Bamboo Cultivation Support",
  ],
  "Nagaland": [
    "🌾 Pradhan Mantri Kisan Samman Nidhi",
    "🌱 Agricultural Support Programs",
    "💧 Irrigation Development",
    "🛡️ Crop Insurance Scheme",
    "🌿 Organic Farming Promotion",
  ],
  "Odisha": [
    "🌾 Pradhan Mantri Kisan Samman Nidhi",
    "🌱 AIBP Irrigation Scheme",
    "💧 PMKSY Micro Irrigation",
    "🛡️ Fasal Bima Yojana",
    "🌿 Pulses Subsidy Scheme",
  ],
  "Punjab": [
    "🌾 Pradhan Mantri Kisan Samman Nidhi",
    "🌱 Smart Agriculture Program",
    "💧 Micro Irrigation Support",
    "🛡️ Government Crop Insurance",
    "🌿 Kissan Credit Card Scheme",
  ],
  "Rajasthan": [
    "🌾 Pradhan Mantri Kisan Samman Nidhi",
    "🌱 Soil Health Mission",
    "💧 Per Drop More Crop PMKSY",
    "🛡️ Fasal Bima Yojana",
    "🌿 Organic Farming Incentive",
  ],
  "Sikkim": [
    "🌾 Pradhan Mantri Kisan Samman Nidhi",
    "🌱 Organic Farming Focus",
    "💧 Irrigation Infrastructure",
    "🛡️ Crop Insurance Yojana",
    "🌿 Horticulture Development",
  ],
  "Tamil Nadu": [
    "🌾 Pradhan Mantri Kisan Samman Nidhi",
    "🌱 Soil Health Card Scheme",
    "💧 PMKSY Irrigation",
    "🛡️ Fasal Bima Yojana",
    "🌿 Agricultural Subsidy Scheme",
  ],
  "Telangana": [
    "🌾 Rytu Bandhu Scheme",
    "🌱 Soil Health Scheme",
    "💧 PMKSY Micro Irrigation",
    "🛡️ Government Crop Insurance",
    "🌿 Agricultural Mechanization",
  ],
  "Tripura": [
    "🌾 Pradhan Mantri Kisan Samman Nidhi",
    "🌱 State Horticulture Mission",
    "💧 Irrigation Development Scheme",
    "🛡️ Crop Insurance Yojana",
    "🌿 Bamboo and Dairy Support",
  ],
  "Uttar Pradesh": [
    "🌾 Pradhan Mantri Kisan Samman Nidhi",
    "🌱 Soil Health Mission",
    "💧 PMKSY Irrigation",
    "🛡️ Fasal Bima Yojana",
    "🌿 Sugarcane Support Scheme",
  ],
  "Uttarakhand": [
    "🌾 Pradhan Mantri Kisan Samman Nidhi",
    "🌱 Horticulture Development",
    "💧 Micro Irrigation Support",
    "🛡️ Crop Insurance Scheme",
    "🌿 Medicinal Plants Support",
  ],
  "West Bengal": [
    "🌾 Pradhan Mantri Kisan Samman Nidhi",
    "🌱 Agricultural Education Support",
    "💧 Irrigation Infrastructure",
    "🛡️ Fasal Bima Yojana",
    "🌿 Fisheries Development Scheme",
  ],
  "Andaman and Nicobar Islands": [
    "🌾 Agro-Based Scheme",
    "🌱 Coconut Development",
    "💧 Irrigation Support",
    "🛡️ Crop Insurance",
    "🌿 Spice Cultivation Support",
  ],
  "Chandigarh": [
    "🌾 Pradhan Mantri Kisan Samman Nidhi",
    "🌱 Urban Horticulture Support",
    "💧 Irrigation Scheme",
    "🛡️ Crop Insurance Yojana",
    "🌿 Nursery Development",
  ],
  "Dadra and Nagar Haveli and Daman and Diu": [
    "🌾 Agricultural Support Scheme",
    "🌱 Horticulture Development",
    "💧 Irrigation Infrastructure",
    "🛡️ Crop Insurance",
    "🌿 Agricultural Mechanization",
  ],
  "Lakshadweep": [
    "🌾 Coconut Cultivation Support",
    "🌱 Horticulture Development",
    "💧 Irrigation Support",
    "🛡️ Fisheries Scheme",
    "🌿 Agricultural Extension Services",
  ],
  "Delhi": [
    "🌾 Pradhan Mantri Kisan Samman Nidhi",
    "🌱 Urban Farming Support",
    "💧 Horticulture Development",
    "🛡️ Crop Insurance Yojana",
    "🌿 Community Farming Scheme",
  ],
  "Puducherry": [
    "🌾 Pradhan Mantri Kisan Samman Nidhi",
    "🌱 Horticulture Support",
    "💧 Irrigation Infrastructure",
    "🛡️ Crop Insurance Scheme",
    "🌿 Coconut Development Board",
  ],
  "Ladakh": [
    "🌾 Pradhan Mantri Kisan Samman Nidhi",
    "🌱 High Altitude Agriculture",
    "💧 Irrigation Development",
    "🛡️ Crop Insurance Support",
    "🌿 Horticulture Promotion",
  ],
  "Jammu and Kashmir": [
    "🌾 Pradhan Mantri Kisan Samman Nidhi",
    "🌱 Saffron Support Scheme",
    "💧 Irrigation Development",
    "🛡️ Crop Insurance Yojana",
    "🌿 Horticulture Development",
  ],
};

export function getStateSchemes(state: string | null): string[] {
  if (!state) return [];
  return STATE_SCHEMES[state as keyof typeof STATE_SCHEMES] || [];
}
